version: "2"

services:

  php:
    # choose the version of PHP you want to work with
    #build: ./docker/php70
    build: ./docker/php71
    volumes:
      - .:/var/www/html
    environment:
      XDEBUG_HOST: ${XDEBUG_HOST}

  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
