version: "2"

services:

  php:
    # choose the version of PHP you want to work with
    #build: ./docker/php70
    build: ./docker/php71nginx
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    environment:
      XDEBUG_HOST: ${XDEBUG_HOST}

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
